import { createReducer, on } from '@ngrx/store';
import { katalogStartAction } from './action';
import { KatalogStateInterface } from '../types/katalogState.interface';




const katalogState: KatalogStateInterface = {
    covrolins: [
        {
            id: 43104,
            sum:'60 484 ₽/м2',
            brand: 'assets/imgs/katalogState/besmer.png',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin1.png'
        },
        {
            id: 43104,
            sum:'60 484 ₽/м2',
            brand: 'assets/imgs/katalogState/besmer.png',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin2.png'
        },
        {
            id: 43104,
            brand: 'assets/imgs/katalogState/besmer.png',
            sum:'60 484 ₽/м2',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin3.png'
        },
        {
            id: 43104,
            sum:'60 484 ₽/м2',
            brand: 'assets/imgs/katalogState/besmer.png',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin4.png'
        },
        {
            id: 43104,
            brand: 'assets/imgs/katalogState/besmer.png',
            sum:'60 484 ₽/м2',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin5.png'
        },
        {
            id: 43104,
            brand: 'assets/imgs/katalogState/besmer.png',
            sum:'60 484 ₽/м2',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin6.png'
        },
        {
            id: 43104,
            brand: 'assets/imgs/katalogState/besmer.png',
            sum:'60 484 ₽/м2',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin7.png'
        },
        {
            id: 43104,
            brand: 'assets/imgs/katalogState/besmer.png',
            sum:'60 484 ₽/м2',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin8.png'
        },
        {
            id: 43104,
            brand: 'assets/imgs/katalogState/besmer.png',
            sum:'60 484 ₽/м2',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin9.png'
        },
        {
            id: 43104,
            sum:'60 484 ₽/м2',
            brand: 'assets/imgs/katalogState/besmer.png',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin10.png'
        },
        {
            id: 43104,
            sum:'60 484 ₽/м2',
            brand: 'assets/imgs/katalogState/besmer.png',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin11.png'
        },
        {
            id: 43104,
            sum:'60 484 ₽/м2',
            brand: 'assets/imgs/katalogState/besmer.png',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin12.png'
        },
        {
            id: 43104,
            sum:'60 484 ₽/м2',
            brand: 'assets/imgs/katalogState/besmer.png',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin13.png'
        },
        {
            id: 43104,
            brand: 'assets/imgs/katalogState/besmer.png',
            sum:'60 484 ₽/м2',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin15.png'
        },
        {
            id: 43104,
            brand: 'assets/imgs/katalogState/besmer.png',
            color: {
                img: 'assets/imgs/katalogState/brown.png',
                color: 'Коричневый',
            },
            country: {
                flag: 'assets/imgs/katalogState/DE.png',
                country: 'Германия'
            },
            collection: 'BESMER Palatino',
            coatingType: 'Коммерческий',
            roomType: ['Гостиницы', 'Кинотеатры и театры', 'Офисы', 'Рестораны', 'клубы'],
            drawingType: 'Не однотонный',
            applications: 33,
            packagingType: 'Полиэтилен',
            ServiceLife: '10 лет',
            formSale: 'Рулон',
            unitMeasurement: 'м²',
            hegiht: '6 мм',
            width: '4 м',
            pileType: 'Велюр',
            totalWeight: '1730 г/м²',
            rollWeight: '173 кг',
            base: 'Джут',
            pileHeight: 3,
            pileComposition: 'Полиамид',
            img:'assets/imgs/katalogState/covrolin8.png',
            sum:'60 484 ₽/м2'
        },
    ]
}


export const katalogReducer = createReducer(
    katalogState, on(katalogStartAction, (state: KatalogStateInterface) => ({ ...state }))
)